services:

  nginx:
    image: beardedtek/newsfeed-nginx:latest
    restart: always
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8880:80"
    volumes:
      - thumbnails:/thumbnails:ro
    depends_on:
      - frontend
      - backend
    networks:
      - newsfeed
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: beardedtek/newsfeed:latest
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - env/frontend
    depends_on:
      - backend
    networks:
      - newsfeed
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    image: beardedtek/newsfeed-backend:latest
    restart: always
    volumes:
      - thumbnails:/thumbnails
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --workers 4
    env_file:
      - env/backend
    depends_on:
      - redis
      - db
    networks:
      - newsfeed
      - casdoor
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  worker:
    image: beardedtek/newsfeed-backend:latest
    restart: always
    volumes:
      - thumbnails:/thumbnails
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runtime
    command: ["celery", "-A", "app.workers.tasks", "worker", "--loglevel=info", "--concurrency=4"]
    env_file:
      - env/backend
    depends_on:
      - redis
      - backend
    networks:
      - newsfeed
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  beat:
    image: beardedtek/newsfeed-backend:latest
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runtime
    command: celery -A app.workers.tasks.celery_app beat --loglevel=info
    env_file:
      - env/backend
    depends_on:
      - redis
      - worker
    networks:
      - newsfeed
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - env/backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - newsfeed
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    restart: always
    command: ["redis-server", "--maxmemory", "512mb", "--maxmemory-policy", "allkeys-lru"]
    networks:
      - newsfeed
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  casdoor:
    image: casbin/casdoor:latest
    restart: always
    environment:
      - ALLOW_ORIGIN=*
    volumes:
      - ./casdoor/app.conf:/conf/app.conf:ro
      - ./casdoor/files:/files
    depends_on:
      - casdoor-db
    networks:
      - newsfeed
      - casdoor
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  casdoor-db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=casdoor
    volumes:
      - newsfeed_casdoor_postgres_data:/var/lib/postgresql/data
    networks:
      - casdoor
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  newsfeed:
    external: true
  casdoor:
    external: true

volumes:
  postgres_data:
  newsfeed_casdoor_postgres_data:
    external: true
  thumbnails:
