services:

  nginx:
    image: beardedtek/newsfeed-nginx:latest
    restart: always
    build:
      context: .
      dockerfile: nginx/Dockerfile
      target: production
    ports:
      - "8880:80"
    volumes:
      - thumbnails:/thumbnails:ro
    depends_on:
      - frontend
      - backend
    networks:
      - newsfeed
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/docs/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  frontend:
    image: beardedtek/newsfeed:latest
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - env/frontend
    depends_on:
      - backend
    networks:
      - newsfeed
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  backend:
    image: beardedtek/newsfeed-backend:latest
    restart: always
    volumes:
      - thumbnails:/thumbnails
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --workers 4
    env_file:
      - env/backend
    depends_on:
      - redis
      - db
    networks:
      - newsfeed
      - casdoor
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  worker:
    image: beardedtek/newsfeed-backend:latest
    restart: always
    volumes:
      - thumbnails:/thumbnails
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runtime
    command: ["celery", "-A", "app.workers.tasks", "worker", "--loglevel=info", "--concurrency=4"]
    env_file:
      - env/backend
    depends_on:
      - redis
      - backend
    networks:
      - newsfeed
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "celery", "-A", "app.workers.tasks", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  beat:
    image: beardedtek/newsfeed-backend:latest
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runtime
    command: celery -A app.workers.tasks.celery_app beat --loglevel=info
    env_file:
      - env/backend
    depends_on:
      - redis
      - worker
    networks:
      - newsfeed
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - env/backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - newsfeed
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    restart: always
    command: ["redis-server", "--maxmemory", "512mb", "--maxmemory-policy", "allkeys-lru"]
    networks:
      - newsfeed
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  casdoor:
    image: casbin/casdoor:latest
    restart: always
    environment:
      - ALLOW_ORIGIN=*
    volumes:
      - ./casdoor/app.conf:/conf/app.conf:ro
      - ./casdoor/init_data.json:/conf/init_data.json:ro
    depends_on:
      - casdoor-db
    networks:
      - newsfeed
      - casdoor
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  casdoor-db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=casdoor
    volumes:
      - newsfeed_casdoor_postgres_data:/var/lib/postgresql/data
    networks:
      - casdoor
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  newsfeed:
    external: true
  casdoor:
    external: true

volumes:
  postgres_data:
  newsfeed_casdoor_postgres_data:
    external: true
  thumbnails:
